name: Python CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 리포지토리 체크아웃
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Python 환경 설정
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: 의존성 설치
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      
      - name: pylint 코드 스타일 검사
        run: |
          pylint $(git ls-files '*.py')
      
      - name: pytest를 사용한 테스트 실행
        run: |
          pytest tests --verbose --junitxml=test-results.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      # Push, Pull request시 테스트를 시행하고 결과를 test-results.xml로 생성함
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.xml

      - name: README.md 자동 생성 
        run: |
          python scripts/generate_readme.py  # ← README 생성 스크립트 실행

      - name: 변경 사항 커밋 및 푸시 
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git diff --cached --quiet || (
            git commit -m "docs: 자동 생성된 README 갱신"  # ← 변경 있을 경우에만 커밋
            git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}  # ← 토큰 푸시
          )
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 